// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Ih0eOv0yY8ZT21kqepceAKtGP0eBA0s',
    appId: '1:382159267499:android:ebf71219794e64ac6f79ee',
    messagingSenderId: '382159267499',
    projectId: 'lor-master-c3b95',
    databaseURL: 'https://lor-master-c3b95-default-rtdb.firebaseio.com',
    storageBucket: 'lor-master-c3b95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFhh5_J_wn0Xn8J65kWiOt82s_dhdyfgo',
    appId: '1:382159267499:ios:68832c81b66e9f966f79ee',
    messagingSenderId: '382159267499',
    projectId: 'lor-master-c3b95',
    databaseURL: 'https://lor-master-c3b95-default-rtdb.firebaseio.com',
    storageBucket: 'lor-master-c3b95.firebasestorage.app',
    iosClientId: '382159267499-npfctmdfn6hj1boehhpd13c6a74tofnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.majorProject',
  );
}
